repos:
  - lifecycle-toolkit
  - lifecycle-toolkit-charts
  - wg-app-lifecycle

# Admins have admin access to the repo
admins:
  - mowies
  - thisthat
  - thschue

# Maintainers have maintain access to the repo
maintainers:
  - thisthat
  - bacherfl
  - RealAnna
  - odubajDT
  - thschue
  - mowies

# Approvers have write access to the repo, the scope is limited in CODEOWNERS
approvers:
  - StackScribe

